// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.1
// source: internal/rpc/rpc.proto

//import "google/protobuf/empty.proto";

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metrics_MetricType int32

const (
	Metrics_UNSPECIFIED Metrics_MetricType = 0
	Metrics_GAUGE       Metrics_MetricType = 1
	Metrics_COUNTER     Metrics_MetricType = 2
)

// Enum value maps for Metrics_MetricType.
var (
	Metrics_MetricType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "GAUGE",
		2: "COUNTER",
	}
	Metrics_MetricType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"GAUGE":       1,
		"COUNTER":     2,
	}
)

func (x Metrics_MetricType) Enum() *Metrics_MetricType {
	p := new(Metrics_MetricType)
	*p = x
	return p
}

func (x Metrics_MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metrics_MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_rpc_rpc_proto_enumTypes[0].Descriptor()
}

func (Metrics_MetricType) Type() protoreflect.EnumType {
	return &file_internal_rpc_rpc_proto_enumTypes[0]
}

func (x Metrics_MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metrics_MetricType.Descriptor instead.
func (Metrics_MetricType) EnumDescriptor() ([]byte, []int) {
	return file_internal_rpc_rpc_proto_rawDescGZIP(), []int{0, 0}
}

type Metrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype Metrics_MetricType `protobuf:"varint,2,opt,name=mtype,proto3,enum=rpc.Metrics_MetricType" json:"mtype,omitempty"`
	Delta int64              `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Value float64            `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_rpc_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_internal_rpc_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Metrics) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metrics) GetMtype() Metrics_MetricType {
	if x != nil {
		return x.Mtype
	}
	return Metrics_UNSPECIFIED
}

func (x *Metrics) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metrics) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CryptMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cryptbuff []byte `protobuf:"bytes,1,opt,name=cryptbuff,proto3" json:"cryptbuff,omitempty"`
	Plainbuff []byte `protobuf:"bytes,2,opt,name=plainbuff,proto3" json:"plainbuff,omitempty"`
}

func (x *CryptMetrics) Reset() {
	*x = CryptMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_rpc_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CryptMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptMetrics) ProtoMessage() {}

func (x *CryptMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptMetrics.ProtoReflect.Descriptor instead.
func (*CryptMetrics) Descriptor() ([]byte, []int) {
	return file_internal_rpc_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *CryptMetrics) GetCryptbuff() []byte {
	if x != nil {
		return x.Cryptbuff
	}
	return nil
}

func (x *CryptMetrics) GetPlainbuff() []byte {
	if x != nil {
		return x.Plainbuff
	}
	return nil
}

type MetricsArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*Metrics `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *MetricsArray) Reset() {
	*x = MetricsArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_rpc_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsArray) ProtoMessage() {}

func (x *MetricsArray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsArray.ProtoReflect.Descriptor instead.
func (*MetricsArray) Descriptor() ([]byte, []int) {
	return file_internal_rpc_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsArray) GetMetrics() []*Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric *Metrics `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
}

func (x *MetricsUpdateResponse) Reset() {
	*x = MetricsUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_rpc_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsUpdateResponse) ProtoMessage() {}

func (x *MetricsUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsUpdateResponse.ProtoReflect.Descriptor instead.
func (*MetricsUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsUpdateResponse) GetMetric() *Metrics {
	if x != nil {
		return x.Metric
	}
	return nil
}

type MetricsUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MetricsUpdatesResponse) Reset() {
	*x = MetricsUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_rpc_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsUpdatesResponse) ProtoMessage() {}

func (x *MetricsUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsUpdatesResponse.ProtoReflect.Descriptor instead.
func (*MetricsUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsUpdatesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_rpc_rpc_proto protoreflect.FileDescriptor

var file_internal_rpc_rpc_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x72,
	0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0xab, 0x01,
	0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x05, 0x6d, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x05, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x41, 0x55, 0x47, 0x45, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x02, 0x22, 0x4a, 0x0a, 0x0c, 0x43,
	0x72, 0x79, 0x70, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x62, 0x75, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x62, 0x75, 0x66, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x69, 0x6e, 0x62, 0x75, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x6c,
	0x61, 0x69, 0x6e, 0x62, 0x75, 0x66, 0x66, 0x22, 0x36, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x26, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22,
	0x3d, 0x0a, 0x15, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x2e,
	0x0a, 0x16, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xe7,
	0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x78, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x32, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x12, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x1a, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0c, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x3e, 0x0a, 0x0c, 0x43, 0x72, 0x79, 0x70,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43,
	0x72, 0x79, 0x70, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x1b, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_rpc_rpc_proto_rawDescOnce sync.Once
	file_internal_rpc_rpc_proto_rawDescData = file_internal_rpc_rpc_proto_rawDesc
)

func file_internal_rpc_rpc_proto_rawDescGZIP() []byte {
	file_internal_rpc_rpc_proto_rawDescOnce.Do(func() {
		file_internal_rpc_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_rpc_rpc_proto_rawDescData)
	})
	return file_internal_rpc_rpc_proto_rawDescData
}

var file_internal_rpc_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_rpc_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_rpc_rpc_proto_goTypes = []interface{}{
	(Metrics_MetricType)(0),        // 0: rpc.Metrics.MetricType
	(*Metrics)(nil),                // 1: rpc.Metrics
	(*CryptMetrics)(nil),           // 2: rpc.CryptMetrics
	(*MetricsArray)(nil),           // 3: rpc.MetricsArray
	(*MetricsUpdateResponse)(nil),  // 4: rpc.MetricsUpdateResponse
	(*MetricsUpdatesResponse)(nil), // 5: rpc.MetricsUpdatesResponse
}
var file_internal_rpc_rpc_proto_depIdxs = []int32{
	0, // 0: rpc.Metrics.mtype:type_name -> rpc.Metrics.MetricType
	1, // 1: rpc.MetricsArray.metrics:type_name -> rpc.Metrics
	1, // 2: rpc.MetricsUpdateResponse.metric:type_name -> rpc.Metrics
	1, // 3: rpc.MetricsExhange.Update:input_type -> rpc.Metrics
	3, // 4: rpc.MetricsExhange.Updates:input_type -> rpc.MetricsArray
	1, // 5: rpc.MetricsExhange.GetValue:input_type -> rpc.Metrics
	2, // 6: rpc.MetricsExhange.CryptUpdates:input_type -> rpc.CryptMetrics
	4, // 7: rpc.MetricsExhange.Update:output_type -> rpc.MetricsUpdateResponse
	5, // 8: rpc.MetricsExhange.Updates:output_type -> rpc.MetricsUpdatesResponse
	1, // 9: rpc.MetricsExhange.GetValue:output_type -> rpc.Metrics
	5, // 10: rpc.MetricsExhange.CryptUpdates:output_type -> rpc.MetricsUpdatesResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_rpc_rpc_proto_init() }
func file_internal_rpc_rpc_proto_init() {
	if File_internal_rpc_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_rpc_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_rpc_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CryptMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_rpc_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_rpc_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_rpc_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_rpc_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_rpc_proto_goTypes,
		DependencyIndexes: file_internal_rpc_rpc_proto_depIdxs,
		EnumInfos:         file_internal_rpc_rpc_proto_enumTypes,
		MessageInfos:      file_internal_rpc_rpc_proto_msgTypes,
	}.Build()
	File_internal_rpc_rpc_proto = out.File
	file_internal_rpc_rpc_proto_rawDesc = nil
	file_internal_rpc_rpc_proto_goTypes = nil
	file_internal_rpc_rpc_proto_depIdxs = nil
}
